src/components/edit/edit.module.css, src/components/edit/edit.tsx, src/components/editRoundFrame/EditRoundFrame.tsx
編集用アイコンを個別で使用できるようにしました(フレームから切り離しました。ログインしてるユーザーidに合わせて表示を切り替えるように使用します。
=> 編集アイコンの作成。

src/pages/new_post/index.tsx
フェッチ方法
ユーザーの入力した値がバリデーションエラーに引っかからなかった場合、articleのタイトル、内容をpostする。
本番の送り先：https://localhost:8080/articles
仮の一旦の送り先：[https://localhost:8000/articles](https://localhost:8080/articles)
ページ内でのデータ送信
非同期関数を用いて、method:””POSTを指定。
サーバーにリクエストの形式をheaderとして伝える。jsonが型への変換。
headers: {
"Content-Type": "application/json",
},
送信リクエストに含めるデータの内容を記載。
body: JSON.stringify({
title: postTitle,
content: postTextarea,
}),
を使って、JavaScript オブジェクトを JSON 文字列に変換。
レスポンスがOKとして帰ってきた場合、作成した投稿の詳細ページに飛ばす。(jsonデータを読み取り、そこからidを取得する)
=> 新規投稿ページ：データの登録と取得

src/components/lists/Lists.tsx
ユーザー投稿一覧画面で使用しているListコンポーネントを修正しました。
リンクタグを削除して、ulタグ全体をクリックした時に画面遷移するよう修正（遷移先は仮置きです🙇）
=> ユーザー投稿一覧ページのエラー解消

db/data.json, src/components/toast/Toast.module.css, src/components/toast/Toast.tsx, src/pages/login/index.tsx
> 変更箇所
* Toast.module.css
* Toast.tsx
* login/index.tsx
> 変更内容
* トーストの不具合を解消
（アニメーションが終わった後に表示されてしまう件）
* トーストを非表示にするクラスを追加して、使うページの条件分岐でクラスを切り替えるように変更
* 本番サーバで起動できるようにコードを追加（現時点コメントアウト）
* ログイン成功したらトーストが表示されるように変更
=> トースト修正、ログインページ変更

src/pages/login/index.tsx, src/pages/register/index.tsx
ログイン画面、新規登録画面で
インポートのエラーが出たので修正しました！
=> インポートコード修正

src/components/usersArticleList/UsersArticleList.tsx, src/pages/mypage/index.tsx, src/pages/mypage/post_list.tsx, src/styles/loginees_post_list.module.css
ログインユーザーの投稿一覧を作成しました。
投稿ごとのフレームをホバーすると色が変わり、クリックすると投稿詳細画面に遷移（そこから編集や削除を行う）するように実装しました。
当初のfigmaで作っていた予定と違いますが、Javaの設計書に合わせていますmm
=> ログインユーザーの投稿一覧を表示

src/pages/login/index.tsx, src/pages/register/confirm.tsx
登録画面にもトーストを追加しました。
登録が完了したらトーストが表示され、ログイン画面に遷移します。
=> 登録画面にトーストの追加

src/components/header/Header.tsx, src/styles/loginees_post_list.module.css
ヘッダーのリンクのパスに誤りがあったため修正しました。
CSSを微修正しました。
=> CSSの微修正、パスの微修正

src/components/lists/Lists.tsx
投稿記事の日付がNaNになっていたところを修正しました
こちらで設定した変数名がバックエンド側で設定した変数名と合っているか確認が必要です🙇
=> 投稿記事の日付の表示

src/components/header/Header.tsx, src/components/usersArticleList/UsersArticleList.tsx, src/pages/login/index.tsx, src/pages/mypage/post_list.tsx
ログインできるようになりました！
他：データがフェッチできないページの修正
[demo_user@example.com](mailto:demo_user@example.com)
パスワード：
tanaka
=> エラーページの修正など

src/components/input/input.module.css, src/pages/register/confirm.tsx
> 変更箇所
* confirm.tsx
> 変更内容
* APIの接続先を変更したため、新規登録できるようになっています。
* 登録アドレスが重複している場合、バックエンド側で登録できないようになっているので、
　エラーメッセージが表示されるように再度修正予定です。
> 画像
登録確認画面
ユーザーデータ
=> 新規登録できるようにコードを修正

src/pages/register/confirm.tsx, src/styles/Register.module.css
> 変更箇所
* register.module.css
* confirm.tsx
> 変更内容
* メールアドレスが重複していた場合にエラーメッセージを表示
> 画像
重複したアドレスを登録しようとした場合
=> ユーザー登録 - エラーメッセージの表示

src/pages/mypage/edit.tsx
本番サーバー用に改修しました。
- Javaの仕様書通りメソッドをPUTに変更
- responseがjson形式ではないため.thenの処理を編集
=> 登録者情報 - 本番サーバーで登録情報の編集ができるように改修

src/pages/register/confirm.tsx, src/pages/register/index.tsx
> 変更箇所
* register.tsx
* register/confirm.tsx
> 変更内容
* 新規登録時に登録ユーザーの情報がURLにのっていた部分を、URLにのせずにデータの受け取りをできるように修正しました。
* 戻るボタンで新規登録ページに戻れるように修正しました。
> 画像
| 変更前 | 変更後 |
| ---- | ---- |
| <img width="1266" alt="変更前" src="https://github.com/user-attachments/assets/d47e1e8a-5f97-41a9-a047-c4e9c1f21698" /> | <img width="1303" alt="変更後" src="https://github.com/user-attachments/assets/0bd5d3c9-acc8-43a0-a1be-06118806910b" /> |
=> 新規登録 - URLに記載されたデータを見えないように修正

src/pages/register/index.tsx
新規登録画面で、氏名を入力していない場合でも登録確認画面に飛んでしまっていたので、
コードを修正しました。
=> 新規登録 - バグ修正

src/pages/post_details/[id].tsx
コメントを更新日、作成日、ID順で昇順に表示するように追加
|コメント追加前|追加後|
| --- | --- |
|![image](https://github.com/user-attachments/assets/fa8e4c64-6871-47e2-8be8-691fe754343b)|![image](https://github.com/user-attachments/assets/0fd63371-fb48-4e88-81a5-3b0901e38444)|
=> コメントを日付、IDの昇順に表示

src/pages/post_details/[id].tsx
未ログイン時、ログインしないとコメントできないよう表示を変更（loginUserIdをnullに変更）
=> 未ログイン時のコメント欄表示

src/components/edit/edit.module.css, src/components/editOnlyRoundFrame/EditRoundFrame.tsx, src/components/editOnlyRoundFrame/editRoundFrame.module.css, src/components/header/Header.tsx, src/components/roundFrame/roundFrame.module.css, src/pages/mypage/index.tsx, src/pages/mypage/post_list.tsx, src/styles/mypage.module.css
いっぺんにいろんな編集をしてしまってすみませんmm
- RoundFrameコンポーネントにホバーが当たっており、不必要に反応していたため削除しました。
- マイページで投稿が0件だった際に、何も表示されないのではなく、メンセージを表示するようにしました。
- 投稿の編集ボタンや削除ボタン上にカーソルが当たった時にカーゾルが指の形になるように変更しました。
- 不要なコンソールログを削除しました（コンソールがすぐいっぱいになってしまうため削除しました。必要だったらすみません、、、！）
- マイページのコードが正しくなかったので修正しました。
=> 無駄に当たっていたホバーの削除、ログインユーザーの投稿が０件だった時のマイページの表示を変更、

package.json, src/components/lists/Lists.tsx, src/components/lists/lists.module.css, src/components/markDown/MarkDown.tsx, src/components/markDown/markDown.module.css, src/pages/mypage/post_list.tsx, src/pages/post_details/[id].tsx, yarn.lock
マークダウン形式からの変換に関して、表やリストが適応されてなかったため修正。
ネスト構造や斜体がまだできてないです・・・アイデア教えてほしいです
=> マークダウンへの変換が一部しかできてなかったため修正

src/components/lists/lists.module.css, src/components/markDown/markDown.module.css
cssを当てたのになんでネストできないのかと思ってたけど見てるとこ違って充てられてなかったです、すみません。多分これで実装完了です
=> ｃｓｓの変更により、ネスト構造やリスト表示の●タイプ変更
